import {
  AdHocConsoleSessionSchema,
  AgentActionSchema,
  AgentActionWorkspaceSchema,
  AgentRunSchema,
  AgentStatusDetailSchema,
  AgentStatusSummarySchema,
  CheckoutSchema,
  ClearMessageHistoryResultSchema,
  ConfigStatusSchema,
  ControlMetadataSchema,
  DeleteGroupResultSchema,
  DeliveryOutcomeSchema,
  ExtensionTrustReceiptSchema,
  GroupMembershipSchema,
  GroupSchema,
  MessagePageSchema,
  MessageSubmissionResultSchema,
  NanasaConfigSchema,
  OpenWaitSchema,
  OperatorSessionSchema,
  PortalSnapshotSchema,
  ProviderCatalogItemSchema,
  ProviderExtensionHealthSchema,
  ProviderExtensionInspectSchema,
  ProviderExtensionPlanSchema,
  ProviderStateBindingSchema,
  RemoveGroupAgentResultSchema,
  ReorderGroupAgentsResultSchema,
  ReorderGroupsResultSchema,
  ReparentGroupAgentResultSchema,
  RepositorySchema,
  RoleDefinitionSchema,
  StartGroupRunsResultSchema,
  TerminalCheckpointContentSchema,
  TerminalCheckpointSchema,
  TerminalEndpointStatusSchema,
  TerminalReadResultSchema,
  WorktreeOperationResultSchema,
  WorktreeSchema,
} from "@nanasa/contracts";
import type { Schema } from "@nanasa/control-client";

export type CliCommandMode = "control" | "local" | "events";
export type CliBodyMode = "none" | "optional" | "required";
export type CliOutputMode = "json" | "text";

export interface CliCommandDeclaration {
  readonly id: string;
  readonly family: string;
  readonly command: string;
  readonly mode: CliCommandMode;
  readonly method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path?: (args: readonly string[]) => string;
  readonly positionals: readonly string[];
  readonly body: CliBodyMode;
  readonly response: Schema<unknown>;
  readonly mutating: boolean;
  readonly output: CliOutputMode;
  readonly summary: string;
}

const UnknownSchema: Schema<unknown> = { parse: (value) => value };
const VoidSchema: Schema<undefined> = { parse: (value) => value as undefined };
const TrustListSchema: Schema<unknown> = UnknownSchema;
const OpenApiSchema: Schema<unknown> = UnknownSchema;

function encoded(args: readonly string[], ...parts: Array<string | number>): string {
  return `/api/v1/${parts
    .map((part) => (typeof part === "number" ? args[part] : part))
    .map((part) => encodeURIComponent(part ?? ""))
    .join("/")}`;
}

function command(
  input: Omit<CliCommandDeclaration, "mode" | "body" | "mutating" | "output"> &
    Partial<Pick<CliCommandDeclaration, "mode" | "body" | "mutating" | "output">>,
): CliCommandDeclaration {
  return Object.freeze({
    mode: "control",
    body: "none",
    mutating: false,
    output: "json",
    ...input,
    positionals: Object.freeze([...input.positionals]),
  });
}

export const CLI_COMMAND_REGISTRY = Object.freeze([
  command({
    id: "daemon.status",
    family: "daemon",
    command: "status",
    method: "GET",
    path: () => "/api/v1/meta",
    positionals: [],
    response: ControlMetadataSchema,
    summary: "Read daemon status",
  }),
  command({
    id: "daemon.open",
    family: "daemon",
    command: "open",
    method: "GET",
    path: () => "/api/v1/meta",
    positionals: [],
    response: ControlMetadataSchema,
    summary: "Resolve the running daemon",
  }),
  command({
    id: "api.meta",
    family: "api",
    command: "meta",
    method: "GET",
    path: () => "/api/v1/meta",
    positionals: [],
    response: ControlMetadataSchema,
    summary: "Read daemon metadata",
  }),
  command({
    id: "api.schema",
    family: "api",
    command: "schema",
    method: "GET",
    path: () => "/api/v1/schema/openapi.json",
    positionals: [],
    response: OpenApiSchema,
    summary: "Read OpenAPI",
  }),
  command({
    id: "api.eventsSchema",
    family: "api",
    command: "events-schema",
    method: "GET",
    path: () => "/api/v1/schema/events.json",
    positionals: [],
    response: OpenApiSchema,
    summary: "Read event JSON Schema",
  }),
  command({
    id: "api.snapshot",
    family: "api",
    command: "snapshot",
    method: "GET",
    path: () => "/api/v1/snapshot",
    positionals: [],
    response: PortalSnapshotSchema,
    summary: "Read atomic snapshot",
  }),
  command({
    id: "metadata.get",
    family: "metadata",
    command: "get",
    method: "GET",
    path: () => "/api/v1/meta",
    positionals: [],
    response: ControlMetadataSchema,
    summary: "Read daemon metadata",
  }),
  command({
    id: "config.show",
    family: "config",
    command: "show",
    method: "GET",
    path: () => "/api/v1/config",
    positionals: [],
    response: NanasaConfigSchema,
    summary: "Read configuration",
  }),
  command({
    id: "config.status",
    family: "config",
    command: "status",
    method: "GET",
    path: () => "/api/v1/config/status",
    positionals: [],
    response: ConfigStatusSchema,
    summary: "Read config diagnostics",
  }),
  command({
    id: "auth.status",
    family: "auth",
    command: "status",
    method: "GET",
    path: () => "/api/v1/auth/session",
    positionals: [],
    response: OperatorSessionSchema,
    summary: "Read operator authentication status",
  }),
  command({
    id: "auth.revoke",
    family: "auth",
    command: "revoke",
    method: "POST",
    path: () => "/api/v1/auth/revoke",
    positionals: [],
    body: "optional",
    response: VoidSchema,
    mutating: true,
    summary: "Revoke current portal session",
  }),
  command({
    id: "auth.login",
    family: "auth",
    command: "login",
    mode: "local",
    positionals: ["integration"],
    response: UnknownSchema,
    summary: "Launch provider authentication",
  }),

  command({
    id: "state.list",
    family: "state",
    command: "list",
    method: "GET",
    path: () => "/api/v1/provider-states",
    positionals: [],
    response: ProviderStateBindingSchema.array(),
    summary: "List provider state",
  }),
  command({
    id: "state.get",
    family: "state",
    command: "get",
    method: "GET",
    path: (a) => encoded(a, "provider-states", 0),
    positionals: ["binding-id"],
    response: ProviderStateBindingSchema,
    summary: "Read provider state",
  }),
  command({
    id: "state.retain",
    family: "state",
    command: "retain",
    method: "POST",
    path: (a) => encoded(a, "provider-states", 0, "retain"),
    positionals: ["binding-id"],
    body: "optional",
    response: ProviderStateBindingSchema,
    mutating: true,
    summary: "Retain provider state",
  }),
  command({
    id: "state.delete",
    family: "state",
    command: "delete",
    method: "DELETE",
    path: (a) => encoded(a, "provider-states", 0),
    positionals: ["binding-id"],
    body: "optional",
    response: ProviderStateBindingSchema,
    mutating: true,
    summary: "Delete provider state",
  }),
  command({
    id: "trust.list",
    family: "trust",
    command: "list",
    method: "GET",
    path: () => "/api/v1/trust",
    positionals: [],
    response: TrustListSchema,
    summary: "List trust receipts",
  }),
  command({
    id: "extension.list",
    family: "extension",
    command: "list",
    method: "GET",
    path: () => "/api/v1/extensions",
    positionals: [],
    response: ProviderCatalogItemSchema.array(),
    summary: "List provider extensions and health",
  }),
  command({
    id: "extension.inspect",
    family: "extension",
    command: "inspect",
    method: "GET",
    path: (a) => encoded(a, "extensions", 0),
    positionals: ["extension-id"],
    response: ProviderExtensionInspectSchema,
    summary: "Inspect one provider extension",
  }),
  command({
    id: "extension.plan",
    family: "extension",
    command: "plan",
    method: "GET",
    path: (a) => encoded(a, "extensions", 0, "plan"),
    positionals: ["extension-id"],
    response: ProviderExtensionPlanSchema,
    summary: "Preview extension permissions and mutations",
  }),
  command({
    id: "extension.health",
    family: "extension",
    command: "health",
    method: "GET",
    path: (a) => encoded(a, "extensions", 0, "health"),
    positionals: ["extension-id"],
    response: ProviderExtensionHealthSchema,
    summary: "Inspect extension health and drift",
  }),
  command({
    id: "extension.trust",
    family: "extension",
    command: "trust",
    method: "POST",
    path: (a) => encoded(a, "extensions", 0, "trust"),
    positionals: ["extension-id"],
    body: "required",
    response: ExtensionTrustReceiptSchema,
    mutating: true,
    summary: "Trust one exact extension plan",
  }),
  ...(["install", "repair", "disable", "rollback"] as const).map((operation) =>
    command({
      id: `extension.${operation}`,
      family: "extension",
      command: operation,
      method: "POST",
      path: (a) => encoded(a, "extensions", 0, operation),
      positionals: ["extension-id"],
      body: "required",
      response: ProviderExtensionInspectSchema,
      mutating: true,
      summary: `${operation[0]!.toUpperCase()}${operation.slice(1)} a declarative provider extension`,
    }),
  ),
  command({
    id: "extension.remove",
    family: "extension",
    command: "remove",
    method: "DELETE",
    path: (a) => encoded(a, "extensions", 0),
    positionals: ["extension-id"],
    body: "required",
    response: ProviderCatalogItemSchema,
    mutating: true,
    summary: "Remove extension lock ownership conservatively",
  }),

  command({
    id: "group.list",
    family: "group",
    command: "list",
    method: "GET",
    path: () => "/api/v1/groups",
    positionals: [],
    response: GroupSchema.array(),
    summary: "List groups",
  }),
  command({
    id: "group.get",
    family: "group",
    command: "get",
    method: "GET",
    path: (a) => encoded(a, "groups", 0),
    positionals: ["group-id"],
    response: GroupSchema,
    summary: "Read group",
  }),
  command({
    id: "group.create",
    family: "group",
    command: "create",
    method: "POST",
    path: () => "/api/v1/groups",
    positionals: [],
    body: "required",
    response: GroupSchema,
    mutating: true,
    summary: "Create group",
  }),
  command({
    id: "group.update",
    family: "group",
    command: "update",
    method: "PATCH",
    path: (a) => encoded(a, "groups", 0),
    positionals: ["group-id"],
    body: "required",
    response: GroupSchema,
    mutating: true,
    summary: "Update group",
  }),
  command({
    id: "group.delete",
    family: "group",
    command: "delete",
    method: "DELETE",
    path: (a) => encoded(a, "groups", 0),
    positionals: ["group-id"],
    body: "optional",
    response: DeleteGroupResultSchema,
    mutating: true,
    summary: "Delete group",
  }),
  command({
    id: "group.reorder",
    family: "group",
    command: "reorder",
    method: "PUT",
    path: () => "/api/v1/group-order",
    positionals: [],
    body: "required",
    response: ReorderGroupsResultSchema,
    mutating: true,
    summary: "Reorder groups",
  }),

  command({
    id: "role.list",
    family: "role",
    command: "list",
    method: "GET",
    path: () => "/api/v1/roles",
    positionals: [],
    response: UnknownSchema,
    summary: "List roles",
  }),
  command({
    id: "role.get",
    family: "role",
    command: "get",
    method: "GET",
    path: (a) => encoded(a, "roles", 0),
    positionals: ["role-id"],
    response: RoleDefinitionSchema,
    summary: "Read role",
  }),
  command({
    id: "role.update",
    family: "role",
    command: "update",
    method: "PATCH",
    path: (a) => encoded(a, "roles", 0, "presentation"),
    positionals: ["role-id"],
    body: "required",
    response: RoleDefinitionSchema,
    mutating: true,
    summary: "Update role presentation",
  }),

  command({
    id: "agent.list",
    family: "agent",
    command: "list",
    method: "GET",
    path: (a) => encoded(a, "groups", 0, "agents"),
    positionals: ["group-id"],
    response: GroupMembershipSchema.array(),
    summary: "List agents",
  }),
  command({
    id: "agent.get",
    family: "agent",
    command: "get",
    method: "GET",
    path: (a) => encoded(a, "groups", 0, "agents", 1),
    positionals: ["group-id", "agent-id"],
    response: GroupMembershipSchema,
    summary: "Read agent",
  }),
  command({
    id: "agent.create",
    family: "agent",
    command: "create",
    method: "POST",
    path: (a) => encoded(a, "groups", 0, "agents"),
    positionals: ["group-id"],
    body: "required",
    response: GroupMembershipSchema,
    mutating: true,
    summary: "Create agent",
  }),
  command({
    id: "agent.update",
    family: "agent",
    command: "update",
    method: "PATCH",
    path: (a) => encoded(a, "groups", 0, "agents", 1),
    positionals: ["group-id", "agent-id"],
    body: "required",
    response: GroupMembershipSchema,
    mutating: true,
    summary: "Update agent",
  }),
  command({
    id: "agent.delete",
    family: "agent",
    command: "delete",
    method: "DELETE",
    path: (a) => encoded(a, "groups", 0, "agents", 1),
    positionals: ["group-id", "agent-id"],
    body: "optional",
    response: RemoveGroupAgentResultSchema,
    mutating: true,
    summary: "Delete agent",
  }),
  command({
    id: "agent.reorder",
    family: "agent",
    command: "reorder",
    method: "PUT",
    path: (a) => encoded(a, "groups", 0, "agent-order"),
    positionals: ["group-id"],
    body: "required",
    response: ReorderGroupAgentsResultSchema,
    mutating: true,
    summary: "Reorder agents",
  }),
  command({
    id: "agent.reparent",
    family: "agent",
    command: "reparent",
    method: "POST",
    path: (a) => encoded(a, "groups", 0, "agents", 1, "reparent"),
    positionals: ["group-id", "agent-id"],
    body: "required",
    response: ReparentGroupAgentResultSchema,
    mutating: true,
    summary: "Reparent stopped agent",
  }),
  command({
    id: "agent.checkout",
    family: "agent",
    command: "checkout",
    method: "PUT",
    path: (a) => encoded(a, "groups", 0, "agents", 1, "checkout"),
    positionals: ["group-id", "agent-id"],
    body: "required",
    response: VoidSchema,
    mutating: true,
    summary: "Assign agent checkout",
  }),
  command({
    id: "agent.prompt",
    family: "agent",
    command: "prompt",
    method: "POST",
    path: () => "/api/v1/agent-actions",
    positionals: [],
    body: "required",
    response: AgentActionSchema,
    mutating: true,
    summary: "Create safe peer prompt",
  }),
  command({
    id: "agent.read",
    family: "agent",
    command: "read",
    method: "GET",
    path: (a) =>
      `${encoded(a, "runs", 0, "terminal", "read")}?generation=${encodeURIComponent(a[1] ?? "")}`,
    positionals: ["run-id", "generation"],
    response: TerminalReadResultSchema,
    output: "text",
    summary: "Read agent terminal",
  }),
  command({
    id: "agent.wait",
    family: "agent",
    command: "wait",
    method: "POST",
    path: (a) => encoded(a, "agent-actions", 0, "wait"),
    positionals: ["action-id"],
    body: "required",
    response: UnknownSchema,
    summary: "Wait for action",
  }),

  command({
    id: "run.list",
    family: "run",
    command: "list",
    method: "GET",
    path: () => "/api/v1/runs",
    positionals: [],
    response: AgentRunSchema.array(),
    summary: "List runs",
  }),
  command({
    id: "run.get",
    family: "run",
    command: "get",
    method: "GET",
    path: (a) => encoded(a, "runs", 0),
    positionals: ["run-id"],
    response: AgentRunSchema,
    summary: "Read run",
  }),
  command({
    id: "run.start",
    family: "run",
    command: "start",
    method: "POST",
    path: (a) => encoded(a, "groups", 0, "agents", 1, "run"),
    positionals: ["group-id", "agent-id"],
    body: "optional",
    response: AgentRunSchema,
    mutating: true,
    summary: "Start run",
  }),
  command({
    id: "run.stop",
    family: "run",
    command: "stop",
    method: "DELETE",
    path: (a) => encoded(a, "groups", 0, "agents", 1, "run"),
    positionals: ["group-id", "agent-id"],
    body: "optional",
    response: AgentRunSchema,
    mutating: true,
    summary: "Stop run",
  }),
  command({
    id: "run.restart",
    family: "run",
    command: "restart",
    method: "POST",
    path: (a) => encoded(a, "runs", 0, "restart"),
    positionals: ["run-id"],
    body: "optional",
    response: AgentRunSchema,
    mutating: true,
    summary: "Restart run",
  }),
  command({
    id: "run.startAll",
    family: "run",
    command: "start-all",
    method: "POST",
    path: (a) => encoded(a, "groups", 0, "runs", "start-all"),
    positionals: ["group-id"],
    body: "optional",
    response: StartGroupRunsResultSchema,
    mutating: true,
    summary: "Start group runs",
  }),
  command({
    id: "run.stopAll",
    family: "run",
    command: "stop-all",
    method: "POST",
    path: (a) => encoded(a, "groups", 0, "runs", "stop-all"),
    positionals: ["group-id"],
    body: "optional",
    response: AgentRunSchema.array(),
    mutating: true,
    summary: "Stop group runs",
  }),
  command({
    id: "run.restartAll",
    family: "run",
    command: "restart-all",
    method: "POST",
    path: (a) => encoded(a, "groups", 0, "runs", "restart-all"),
    positionals: ["group-id"],
    body: "optional",
    response: AgentRunSchema.array(),
    mutating: true,
    summary: "Restart group runs",
  }),
  command({
    id: "run.interrupt",
    family: "run",
    command: "interrupt",
    method: "POST",
    path: (a) => encoded(a, "runs", 0, "interrupt"),
    positionals: ["run-id"],
    body: "optional",
    response: VoidSchema,
    mutating: true,
    summary: "Interrupt run",
  }),

  command({
    id: "status.list",
    family: "status",
    command: "list",
    method: "GET",
    path: (a) =>
      a[0] === undefined
        ? "/api/v1/statuses"
        : `/api/v1/statuses?groupId=${encodeURIComponent(a[0])}`,
    positionals: [],
    response: AgentStatusSummarySchema.array(),
    summary: "List status",
  }),
  command({
    id: "status.get",
    family: "status",
    command: "get",
    method: "GET",
    path: (a) => encoded(a, "groups", 0, "members", 1, "status"),
    positionals: ["group-id", "member-id"],
    response: AgentStatusDetailSchema,
    summary: "Read status",
  }),
  command({
    id: "status.ack",
    family: "status",
    command: "ack",
    method: "POST",
    path: (a) => encoded(a, "groups", 0, "members", 1, "status", "acknowledge"),
    positionals: ["group-id", "member-id"],
    body: "optional",
    response: AgentStatusDetailSchema,
    mutating: true,
    summary: "Acknowledge completion",
  }),

  command({
    id: "message.send",
    family: "message",
    command: "send",
    method: "POST",
    path: (a) => encoded(a, "groups", 0, "messages"),
    positionals: ["group-id"],
    body: "required",
    response: MessageSubmissionResultSchema,
    mutating: true,
    summary: "Send durable message",
  }),
  command({
    id: "message.list",
    family: "message",
    command: "list",
    method: "GET",
    path: (a) => encoded(a, "groups", 0, "messages"),
    positionals: ["group-id"],
    response: MessagePageSchema,
    summary: "List messages",
  }),
  command({
    id: "message.deliveries",
    family: "message",
    command: "deliveries",
    method: "GET",
    path: (a) => encoded(a, "messages", 0, "deliveries"),
    positionals: ["message-id"],
    response: DeliveryOutcomeSchema.array(),
    summary: "List deliveries",
  }),
  command({
    id: "message.clear",
    family: "message",
    command: "clear",
    method: "DELETE",
    path: (a) => encoded(a, "groups", 0, "messages"),
    positionals: ["group-id"],
    body: "optional",
    response: ClearMessageHistoryResultSchema,
    mutating: true,
    summary: "Clear messages",
  }),

  command({
    id: "action.create",
    family: "action",
    command: "create",
    method: "POST",
    path: () => "/api/v1/agent-actions",
    positionals: [],
    body: "required",
    response: AgentActionSchema,
    mutating: true,
    summary: "Create action",
  }),
  command({
    id: "action.get",
    family: "action",
    command: "get",
    method: "GET",
    path: (a) => encoded(a, "agent-actions", 0),
    positionals: ["action-id"],
    response: AgentActionSchema,
    summary: "Read action",
  }),
  command({
    id: "action.list",
    family: "action",
    command: "list",
    method: "GET",
    path: (a) => encoded(a, "groups", 0, "action-workspace"),
    positionals: ["group-id"],
    response: AgentActionWorkspaceSchema,
    summary: "List action workspace",
  }),
  command({
    id: "action.wait",
    family: "action",
    command: "wait",
    method: "POST",
    path: (a) => encoded(a, "agent-actions", 0, "wait"),
    positionals: ["action-id"],
    body: "required",
    response: UnknownSchema,
    summary: "Wait for action",
  }),
  command({
    id: "action.cancel",
    family: "action",
    command: "cancel",
    method: "POST",
    path: (a) => encoded(a, "agent-actions", 0, "cancel"),
    positionals: ["action-id"],
    body: "optional",
    response: AgentActionSchema,
    mutating: true,
    summary: "Cancel action",
  }),
  command({
    id: "wait.list",
    family: "wait",
    command: "list",
    method: "GET",
    path: (a) =>
      `/api/v1/open-waits?groupId=${encodeURIComponent(a[0] ?? "")}${a[1] === undefined ? "" : `&memberId=${encodeURIComponent(a[1])}`}`,
    positionals: ["group-id"],
    response: OpenWaitSchema.array(),
    summary: "List open waits",
  }),
  command({
    id: "wait.reply",
    family: "wait",
    command: "reply",
    method: "POST",
    path: (a) => encoded(a, "open-waits", 0, "reply"),
    positionals: ["wait-id"],
    body: "required",
    response: OpenWaitSchema,
    mutating: true,
    summary: "Reply to exact wait",
  }),

  command({
    id: "terminal.status",
    family: "terminal",
    command: "status",
    method: "GET",
    path: (a) => encoded(a, "runs", 0, "terminal"),
    positionals: ["run-id"],
    response: TerminalEndpointStatusSchema,
    summary: "Read terminal status",
  }),
  command({
    id: "terminal.read",
    family: "terminal",
    command: "read",
    method: "GET",
    path: (a) =>
      `${encoded(a, "runs", 0, "terminal", "read")}?generation=${encodeURIComponent(a[1] ?? "")}`,
    positionals: ["run-id", "generation"],
    response: TerminalReadResultSchema,
    output: "text",
    summary: "Read terminal history",
  }),
  command({
    id: "terminal.open",
    family: "terminal",
    command: "open",
    method: "GET",
    path: (a) => encoded(a, "runs", 0, "terminal"),
    positionals: ["run-id"],
    response: TerminalEndpointStatusSchema,
    summary: "Resolve terminal stream",
  }),
  command({
    id: "terminal.checkpoints",
    family: "terminal",
    command: "checkpoints",
    method: "GET",
    path: () => "/api/v1/terminal-checkpoints",
    positionals: [],
    response: TerminalCheckpointSchema.array(),
    summary: "List checkpoints",
  }),
  command({
    id: "terminal.checkpoint",
    family: "terminal",
    command: "checkpoint",
    method: "GET",
    path: (a) => encoded(a, "terminal-checkpoints", 0),
    positionals: ["checkpoint-id"],
    response: TerminalCheckpointContentSchema,
    summary: "Read checkpoint",
  }),

  command({
    id: "console.list",
    family: "console",
    command: "list",
    method: "GET",
    path: () => "/api/v1/consoles",
    positionals: [],
    response: AdHocConsoleSessionSchema.array(),
    summary: "List consoles",
  }),
  command({
    id: "console.get",
    family: "console",
    command: "get",
    method: "GET",
    path: (a) => encoded(a, "consoles", 0),
    positionals: ["console-id"],
    response: AdHocConsoleSessionSchema,
    summary: "Read console",
  }),
  command({
    id: "console.create",
    family: "console",
    command: "create",
    method: "POST",
    path: () => "/api/v1/consoles",
    positionals: [],
    body: "optional",
    response: AdHocConsoleSessionSchema,
    mutating: true,
    summary: "Create console",
  }),
  command({
    id: "console.delete",
    family: "console",
    command: "delete",
    method: "DELETE",
    path: (a) => encoded(a, "consoles", 0),
    positionals: ["console-id"],
    body: "optional",
    response: VoidSchema,
    mutating: true,
    summary: "Delete console",
  }),

  command({
    id: "checkout.repositories",
    family: "checkout",
    command: "repositories",
    method: "GET",
    path: () => "/api/v1/repositories",
    positionals: [],
    response: RepositorySchema.array(),
    summary: "List repositories",
  }),
  command({
    id: "checkout.list",
    family: "checkout",
    command: "list",
    method: "GET",
    path: (a) => encoded(a, "repositories", 0, "checkouts"),
    positionals: ["repository-id"],
    response: CheckoutSchema.array(),
    summary: "List checkouts",
  }),
  command({
    id: "checkout.open",
    family: "checkout",
    command: "open",
    method: "POST",
    path: () => "/api/v1/checkouts/open",
    positionals: [],
    body: "required",
    response: WorktreeOperationResultSchema,
    mutating: true,
    summary: "Open checkout",
  }),
  command({
    id: "checkout.assign",
    family: "checkout",
    command: "assign",
    method: "PUT",
    path: (a) => encoded(a, "groups", 0, "agents", 1, "checkout"),
    positionals: ["group-id", "agent-id"],
    body: "required",
    response: VoidSchema,
    mutating: true,
    summary: "Assign checkout",
  }),
  command({
    id: "worktree.list",
    family: "worktree",
    command: "list",
    method: "GET",
    path: (a) => encoded(a, "repositories", 0, "worktrees"),
    positionals: ["repository-id"],
    response: WorktreeSchema.array(),
    summary: "List worktrees",
  }),
  command({
    id: "worktree.create",
    family: "worktree",
    command: "create",
    method: "POST",
    path: () => "/api/v1/worktrees",
    positionals: [],
    body: "required",
    response: WorktreeOperationResultSchema,
    mutating: true,
    summary: "Create worktree",
  }),
  command({
    id: "worktree.remove",
    family: "worktree",
    command: "remove",
    method: "DELETE",
    path: (a) => encoded(a, "worktrees", 0),
    positionals: ["worktree-id"],
    body: "required",
    response: WorktreeOperationResultSchema,
    mutating: true,
    summary: "Remove worktree",
  }),

  command({
    id: "events.watch",
    family: "events",
    command: "watch",
    mode: "events",
    positionals: [],
    response: UnknownSchema,
    summary: "Watch sequenced events",
  }),
  ...(
    ["install", "status", "start", "stop", "restart", "remove", "logs", "wait-ready"] as const
  ).map((operation) =>
    command({
      id: `service.${operation}`,
      family: "service",
      command: operation,
      mode: "local",
      positionals: [],
      response: UnknownSchema,
      summary: `${operation[0]!.toUpperCase()}${operation.slice(1)} the project-local systemd user service`,
    }),
  ),
  command({
    id: "service.upgrade",
    family: "service",
    command: "upgrade",
    mode: "local",
    positionals: ["candidate-package-root"],
    response: UnknownSchema,
    summary: "Atomically upgrade package and state with readiness rollback",
  }),
  command({
    id: "service.rollback",
    family: "service",
    command: "rollback",
    mode: "local",
    positionals: ["backup-id"],
    response: UnknownSchema,
    summary: "Restore one verified package-state backup",
  }),
  command({
    id: "migration.probe",
    family: "migration",
    command: "probe",
    mode: "local",
    positionals: [],
    response: UnknownSchema,
    summary: "Probe schema and integrity without mutation",
  }),
  command({
    id: "migration.apply",
    family: "migration",
    command: "apply",
    mode: "local",
    positionals: [],
    response: UnknownSchema,
    summary: "Apply the complete supported migration path",
  }),
  command({
    id: "remote.describe",
    family: "remote",
    command: "describe",
    mode: "local",
    positionals: [],
    response: UnknownSchema,
    summary: "Describe exact repository service and protocol identity",
  }),
  command({
    id: "remote.connect",
    family: "remote",
    command: "connect",
    mode: "local",
    positionals: ["ssh-target"],
    response: UnknownSchema,
    summary: "Open a loopback-only OpenSSH portal tunnel",
  }),
  ...(["start", "restart"] as const).map((operation) =>
    command({
      id: `remote.${operation}`,
      family: "remote",
      command: operation,
      mode: "local",
      positionals: ["ssh-target"],
      response: UnknownSchema,
      summary: `${operation === "start" ? "Start" : "Restart"} the remote project service through OpenSSH`,
    }),
  ),
  command({
    id: "doctor.run",
    family: "doctor",
    command: "run",
    mode: "local",
    positionals: [],
    response: UnknownSchema,
    summary: "Run local diagnostics",
  }),
  command({
    id: "completion.generate",
    family: "completion",
    command: "generate",
    mode: "local",
    positionals: ["shell"],
    response: UnknownSchema,
    summary: "Generate shell completion",
  }),
] satisfies readonly CliCommandDeclaration[]);

const commandByName = new Map(
  CLI_COMMAND_REGISTRY.map((item) => [`${item.family}:${item.command}`, item]),
);

export function findCliCommand(family: string, name: string): CliCommandDeclaration | undefined {
  return commandByName.get(`${family}:${name}`);
}

export function commandRegistryHelp(): string {
  const families = new Map<string, CliCommandDeclaration[]>();
  for (const item of CLI_COMMAND_REGISTRY) {
    const entries = families.get(item.family) ?? [];
    entries.push(item);
    families.set(item.family, entries);
  }
  return [...families.entries()]
    .map(([family, entries]) => `${family}: ${entries.map((item) => item.command).join(", ")}`)
    .join("\n");
}
