import {
  AdHocConsoleSessionSchema,
  AgentActionSchema,
  AgentActionWorkspaceSchema,
  AgentRunSchema,
  AgentStatusDetailSchema,
  AgentStatusSummarySchema,
  AssignAgentCheckoutCommandSchema,
  BrowserRestartFrameSchema,
  CheckoutSchema,
  ClearMessageHistoryResultSchema,
  ConfigStatusSchema,
  ControlMetadataSchema,
  CreateAgentActionCommandSchema,
  CreateGroupAgentCommandSchema,
  CreateGroupCommandSchema,
  CreateWorktreeCommandSchema,
  DeleteGroupResultSchema,
  DeliveryOutcomeSchema,
  ExtensionLifecycleCommandSchema,
  ExtensionTrustReceiptSchema,
  GroupMembershipSchema,
  GroupSchema,
  InstallProviderExtensionCommandSchema,
  InterruptAgentRunCommandSchema,
  MessagePageSchema,
  MessageSubmissionResultSchema,
  NanasaConfigSchema,
  OpenCheckoutCommandSchema,
  OpenWaitSchema,
  OperatorBootstrapCommandSchema,
  OperatorSessionSchema,
  PortalSnapshotSchema,
  ProviderCatalogItemSchema,
  ProviderExtensionHealthSchema,
  ProviderExtensionInspectSchema,
  ProviderExtensionPlanSchema,
  ProviderExtensionReferenceSchema,
  ProviderStateBindingSchema,
  RemoteDescriptorSchema,
  RemoveGroupAgentResultSchema,
  RemoveWorktreeCommandSchema,
  ReorderGroupAgentsCommandSchema,
  ReorderGroupAgentsResultSchema,
  ReorderGroupsCommandSchema,
  ReorderGroupsResultSchema,
  RepairProviderExtensionCommandSchema,
  ReparentGroupAgentCommandSchema,
  ReparentGroupAgentResultSchema,
  ReplyOpenWaitCommandSchema,
  RepositorySchema,
  RoleDefinitionSchema,
  ServiceDescriptorSchema,
  StartAgentRunCommandSchema,
  StartGroupRunsCommandSchema,
  StartGroupRunsResultSchema,
  StopAgentRunCommandSchema,
  SubmitMessageCommandSchema,
  TerminalCheckpointCaptureSchema,
  TerminalCheckpointContentSchema,
  TerminalCheckpointSchema,
  TerminalEndpointStatusSchema,
  TerminalReadResultSchema,
  TrustProviderExtensionCommandSchema,
  UpdateGroupAgentCommandSchema,
  UpdateGroupCommandSchema,
  UpdateRolePresentationCommandSchema,
  WaitForAgentActionCommandSchema,
  WorktreeOperationResultSchema,
  WorktreeSchema,
} from "@nanasa/contracts";
import { z } from "zod";

export type ControlRouteMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
export type ControlPrincipal = "public" | "operator";
export type IdempotencyPolicy = "forbidden" | "optional" | "required";

export interface ControlRouteDeclaration {
  readonly id: string;
  readonly family: string;
  readonly method: ControlRouteMethod;
  readonly path: `/api/v1${string}`;
  readonly principal: ControlPrincipal;
  readonly schemas: {
    readonly params: z.ZodType;
    readonly query: z.ZodType;
    readonly body: z.ZodType;
    readonly response: z.ZodType;
  };
  readonly bodyLimit: number;
  readonly idempotency: IdempotencyPolicy;
  readonly errors: readonly string[];
  readonly openapi: {
    readonly operationId: string;
    readonly summary: string;
    readonly tags: readonly string[];
    readonly successStatus: number;
  };
  readonly transport?: "http" | "websocket";
}

const KiB = 1_024;
const EmptySchema = z.undefined();
const EmptyObjectSchema = z.object({}).strict();
const IdParamsSchema = z.record(z.string(), z.string().trim().min(1).max(4_096));
const EmptyQuerySchema = EmptyObjectSchema;
const StringQuerySchema = z.record(z.string(), z.string().max(4_096).optional());
const UnknownObjectSchema = z.record(z.string(), z.unknown());
const TrustReceiptSchema = z
  .object({
    id: z.string(),
    repositoryIdentity: z.string(),
    subjectDigest: z.string(),
    principalId: z.string(),
    decision: z.enum(["trusted", "denied", "revoked"]),
    decidedAt: z.string(),
    revokedAt: z.string().optional(),
  })
  .strict();

interface RouteInput {
  id: string;
  family: string;
  method: ControlRouteMethod;
  path: `/api/v1${string}`;
  principal?: ControlPrincipal;
  params?: z.ZodType;
  query?: z.ZodType;
  body?: z.ZodType;
  response?: z.ZodType;
  bodyLimit?: number;
  idempotency?: IdempotencyPolicy;
  errors?: readonly string[];
  summary: string;
  successStatus?: number;
  transport?: "http" | "websocket";
}

function route(input: RouteInput): ControlRouteDeclaration {
  if (input.method !== "GET" && input.idempotency === undefined) {
    throw new Error(`State-changing route ${input.id} must declare an idempotency policy`);
  }
  return Object.freeze({
    id: input.id,
    family: input.family,
    method: input.method,
    path: input.path,
    principal: input.principal ?? "operator",
    schemas: Object.freeze({
      params: input.params ?? EmptyObjectSchema,
      query: input.query ?? EmptyQuerySchema,
      body: input.body ?? EmptySchema,
      response: input.response ?? EmptySchema,
    }),
    bodyLimit: input.bodyLimit ?? 64 * KiB,
    idempotency: input.idempotency ?? "forbidden",
    errors: Object.freeze([...(input.errors ?? [])]),
    openapi: Object.freeze({
      operationId: input.id,
      summary: input.summary,
      tags: Object.freeze([input.family]),
      successStatus: input.successStatus ?? 200,
    }),
    ...(input.transport === undefined ? {} : { transport: input.transport }),
  });
}

export const CONTROL_ROUTE_REGISTRY = Object.freeze([
  route({
    id: "meta.get",
    family: "metadata",
    method: "GET",
    path: "/api/v1/meta",
    principal: "public",
    response: ControlMetadataSchema,
    summary: "Read daemon protocol metadata",
  }),
  route({
    id: "schema.openapi",
    family: "metadata",
    method: "GET",
    path: "/api/v1/schema/openapi.json",
    principal: "public",
    response: UnknownObjectSchema,
    summary: "Read the generated OpenAPI document",
  }),
  route({
    id: "schema.events",
    family: "metadata",
    method: "GET",
    path: "/api/v1/schema/events.json",
    principal: "public",
    response: UnknownObjectSchema,
    summary: "Read the generated event-frame JSON Schema",
  }),
  route({
    id: "schema.extensions",
    family: "metadata",
    method: "GET",
    path: "/api/v1/schema/extensions.json",
    principal: "public",
    response: ProviderExtensionReferenceSchema,
    summary: "Read generated provider extension schema and capability references",
  }),
  route({
    id: "auth.bootstrap",
    family: "auth",
    method: "POST",
    path: "/api/v1/auth/bootstrap",
    principal: "public",
    body: OperatorBootstrapCommandSchema,
    response: OperatorSessionSchema,
    idempotency: "forbidden",
    errors: ["operator_bootstrap_invalid"],
    summary: "Exchange a one-use portal bootstrap token",
  }),
  route({
    id: "auth.session",
    family: "auth",
    method: "GET",
    path: "/api/v1/auth/session",
    response: OperatorSessionSchema,
    errors: ["operator_unauthorized"],
    summary: "Read the current operator session",
  }),
  route({
    id: "auth.revoke",
    family: "auth",
    method: "POST",
    path: "/api/v1/auth/revoke",
    body: EmptyObjectSchema,
    response: EmptySchema,
    idempotency: "forbidden",
    errors: ["operator_unauthorized"],
    summary: "Revoke the current operator session",
    successStatus: 204,
  }),
  route({
    id: "config.get",
    family: "config",
    method: "GET",
    path: "/api/v1/config",
    response: NanasaConfigSchema,
    summary: "Read the version 2 configuration",
  }),
  route({
    id: "config.status",
    family: "config",
    method: "GET",
    path: "/api/v1/config/status",
    response: ConfigStatusSchema,
    summary: "Read configuration diagnostics",
  }),
  route({
    id: "snapshot.get",
    family: "metadata",
    method: "GET",
    path: "/api/v1/snapshot",
    response: PortalSnapshotSchema,
    summary: "Read an atomic control-plane snapshot",
  }),
  route({
    id: "service.status",
    family: "service",
    method: "GET",
    path: "/api/v1/service",
    response: ServiceDescriptorSchema,
    summary: "Read project-local service health and continuity policy",
  }),
  route({
    id: "service.planRestart",
    family: "service",
    method: "POST",
    path: "/api/v1/service/restart-plan",
    body: z.object({ reason: z.enum(["upgrade", "rollback", "operator-restart"]) }).strict(),
    response: BrowserRestartFrameSchema,
    idempotency: "optional",
    summary: "Create a typed browser reconnect and resnapshot plan",
  }),
  route({
    id: "remote.status",
    family: "remote",
    method: "GET",
    path: "/api/v1/remote",
    response: RemoteDescriptorSchema,
    summary: "Read exact loopback remote discovery identity",
  }),

  route({
    id: "state.list",
    family: "state",
    method: "GET",
    path: "/api/v1/provider-states",
    response: ProviderStateBindingSchema.array(),
    summary: "List provider-state bindings",
  }),
  route({
    id: "state.get",
    family: "state",
    method: "GET",
    path: "/api/v1/provider-states/:bindingId",
    params: IdParamsSchema,
    response: ProviderStateBindingSchema,
    errors: ["provider_state_not_found"],
    summary: "Read one provider-state binding",
  }),
  route({
    id: "state.retain",
    family: "state",
    method: "POST",
    path: "/api/v1/provider-states/:bindingId/retain",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: ProviderStateBindingSchema,
    idempotency: "optional",
    errors: ["provider_state_not_found"],
    summary: "Retain one provider-state binding",
  }),
  route({
    id: "state.delete",
    family: "state",
    method: "DELETE",
    path: "/api/v1/provider-states/:bindingId",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: ProviderStateBindingSchema,
    idempotency: "optional",
    errors: ["provider_state_not_found"],
    summary: "Mark one provider-state binding deleted",
  }),
  route({
    id: "trust.list",
    family: "trust",
    method: "GET",
    path: "/api/v1/trust",
    response: TrustReceiptSchema.array(),
    summary: "List redacted repository trust decisions",
  }),

  route({
    id: "extensions.catalog",
    family: "extension",
    method: "GET",
    path: "/api/v1/catalog/providers",
    response: ProviderCatalogItemSchema.array(),
    summary: "List metadata-only provider extension catalog entries",
  }),
  route({
    id: "extensions.list",
    family: "extension",
    method: "GET",
    path: "/api/v1/extensions",
    response: ProviderCatalogItemSchema.array(),
    summary: "List installed and available provider extensions",
  }),
  route({
    id: "extensions.inspect",
    family: "extension",
    method: "GET",
    path: "/api/v1/extensions/:extensionId",
    params: IdParamsSchema,
    response: ProviderExtensionInspectSchema,
    errors: ["extension_not_found"],
    summary: "Inspect one provider extension",
  }),
  route({
    id: "extensions.plan",
    family: "extension",
    method: "GET",
    path: "/api/v1/extensions/:extensionId/plan",
    params: IdParamsSchema,
    response: ProviderExtensionPlanSchema,
    errors: ["extension_not_found"],
    summary: "Preview permissions, commands, ownership, and mutations",
  }),
  route({
    id: "extensions.health",
    family: "extension",
    method: "GET",
    path: "/api/v1/extensions/:extensionId/health",
    params: IdParamsSchema,
    response: ProviderExtensionHealthSchema,
    errors: ["extension_not_found"],
    summary: "Read provider extension health and drift",
  }),
  route({
    id: "extensions.trust",
    family: "extension",
    method: "POST",
    path: "/api/v1/extensions/:extensionId/trust",
    params: IdParamsSchema,
    body: TrustProviderExtensionCommandSchema,
    response: ExtensionTrustReceiptSchema,
    idempotency: "forbidden",
    errors: ["extension_plan_stale"],
    summary: "Trust one exact provider extension plan",
  }),
  route({
    id: "extensions.install",
    family: "extension",
    method: "POST",
    path: "/api/v1/extensions/:extensionId/install",
    params: IdParamsSchema,
    body: InstallProviderExtensionCommandSchema,
    response: ProviderExtensionInspectSchema,
    idempotency: "forbidden",
    errors: ["extension_trust_required", "extension_plan_stale", "extension_active_runs"],
    summary: "Install or update one trusted declarative provider extension",
  }),
  route({
    id: "extensions.repair",
    family: "extension",
    method: "POST",
    path: "/api/v1/extensions/:extensionId/repair",
    params: IdParamsSchema,
    body: RepairProviderExtensionCommandSchema,
    response: ProviderExtensionInspectSchema,
    idempotency: "forbidden",
    errors: ["extension_not_installed", "extension_active_runs"],
    summary: "Repair only Nanasa-owned provider extension state",
  }),
  route({
    id: "extensions.disable",
    family: "extension",
    method: "POST",
    path: "/api/v1/extensions/:extensionId/disable",
    params: IdParamsSchema,
    body: ExtensionLifecycleCommandSchema,
    response: ProviderExtensionInspectSchema,
    idempotency: "forbidden",
    errors: ["extension_not_installed", "extension_active_runs"],
    summary: "Disable a stopped provider extension",
  }),
  route({
    id: "extensions.rollback",
    family: "extension",
    method: "POST",
    path: "/api/v1/extensions/:extensionId/rollback",
    params: IdParamsSchema,
    body: ExtensionLifecycleCommandSchema,
    response: ProviderExtensionInspectSchema,
    idempotency: "forbidden",
    errors: ["extension_rollback_unavailable", "extension_active_runs"],
    summary: "Roll back to the previous exact provider extension generation",
  }),
  route({
    id: "extensions.remove",
    family: "extension",
    method: "DELETE",
    path: "/api/v1/extensions/:extensionId",
    params: IdParamsSchema,
    body: ExtensionLifecycleCommandSchema,
    response: ProviderCatalogItemSchema,
    idempotency: "forbidden",
    errors: ["extension_referenced", "extension_active_runs"],
    summary: "Remove lock ownership without deleting provider-owned data",
  }),

  route({
    id: "groups.list",
    family: "group",
    method: "GET",
    path: "/api/v1/groups",
    response: GroupSchema.array(),
    summary: "List groups in canonical order",
  }),
  route({
    id: "groups.get",
    family: "group",
    method: "GET",
    path: "/api/v1/groups/:groupId",
    params: IdParamsSchema,
    response: GroupSchema,
    errors: ["group_not_found"],
    summary: "Read one group",
  }),
  route({
    id: "groups.create",
    family: "group",
    method: "POST",
    path: "/api/v1/groups",
    body: CreateGroupCommandSchema,
    response: GroupSchema,
    idempotency: "forbidden",
    errors: ["validation_error"],
    summary: "Create a group",
    successStatus: 201,
  }),
  route({
    id: "groups.update",
    family: "group",
    method: "PATCH",
    path: "/api/v1/groups/:groupId",
    params: IdParamsSchema,
    body: UpdateGroupCommandSchema,
    response: GroupSchema,
    idempotency: "forbidden",
    errors: ["group_not_found", "active_run_group_change_requires_restart"],
    summary: "Update a group",
  }),
  route({
    id: "groups.delete",
    family: "group",
    method: "DELETE",
    path: "/api/v1/groups/:groupId",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: DeleteGroupResultSchema,
    idempotency: "forbidden",
    errors: ["group_not_found"],
    summary: "Delete a stopped group",
  }),
  route({
    id: "groups.reorder",
    family: "group",
    method: "PUT",
    path: "/api/v1/group-order",
    body: ReorderGroupsCommandSchema,
    response: ReorderGroupsResultSchema,
    idempotency: "forbidden",
    errors: ["topology_order_stale"],
    summary: "Replace canonical group order",
  }),

  route({
    id: "agents.list",
    family: "agent",
    method: "GET",
    path: "/api/v1/groups/:groupId/agents",
    params: IdParamsSchema,
    response: GroupMembershipSchema.array(),
    errors: ["group_not_found"],
    summary: "List configured agents in canonical order",
  }),
  route({
    id: "agents.get",
    family: "agent",
    method: "GET",
    path: "/api/v1/groups/:groupId/agents/:agentId",
    params: IdParamsSchema,
    response: GroupMembershipSchema,
    errors: ["agent_not_found"],
    summary: "Read one configured agent",
  }),
  route({
    id: "agents.create",
    family: "agent",
    method: "POST",
    path: "/api/v1/groups/:groupId/agents",
    params: IdParamsSchema,
    body: CreateGroupAgentCommandSchema,
    response: GroupMembershipSchema,
    idempotency: "forbidden",
    errors: ["group_not_found", "integration_not_found"],
    summary: "Create a configured agent",
    successStatus: 201,
  }),
  route({
    id: "agents.update",
    family: "agent",
    method: "PATCH",
    path: "/api/v1/groups/:groupId/agents/:agentId",
    params: IdParamsSchema,
    body: UpdateGroupAgentCommandSchema,
    response: GroupMembershipSchema,
    idempotency: "forbidden",
    errors: ["agent_not_found", "active_run_agent_change_requires_restart"],
    summary: "Update a configured agent",
  }),
  route({
    id: "agents.delete",
    family: "agent",
    method: "DELETE",
    path: "/api/v1/groups/:groupId/agents/:agentId",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: RemoveGroupAgentResultSchema,
    idempotency: "forbidden",
    errors: ["agent_not_found"],
    summary: "Delete a configured agent",
  }),
  route({
    id: "agents.reorder",
    family: "agent",
    method: "PUT",
    path: "/api/v1/groups/:groupId/agent-order",
    params: IdParamsSchema,
    body: ReorderGroupAgentsCommandSchema,
    response: ReorderGroupAgentsResultSchema,
    idempotency: "forbidden",
    errors: ["topology_order_stale"],
    summary: "Replace canonical agent order",
  }),
  route({
    id: "agents.reparent",
    family: "agent",
    method: "POST",
    path: "/api/v1/groups/:groupId/agents/:agentId/reparent",
    params: IdParamsSchema,
    body: ReparentGroupAgentCommandSchema,
    response: ReparentGroupAgentResultSchema,
    idempotency: "forbidden",
    errors: ["active_run_reparent_forbidden", "topology_order_stale"],
    summary: "Move a stopped agent between groups",
  }),
  route({
    id: "agents.assignCheckout",
    family: "checkout",
    method: "PUT",
    path: "/api/v1/groups/:groupId/agents/:agentId/checkout",
    params: IdParamsSchema,
    body: AssignAgentCheckoutCommandSchema,
    response: EmptySchema,
    idempotency: "forbidden",
    errors: ["active_run_checkout_change_forbidden", "checkout_not_found"],
    summary: "Assign a checkout to a stopped agent",
    successStatus: 204,
  }),

  route({
    id: "roles.list",
    family: "role",
    method: "GET",
    path: "/api/v1/roles",
    response: z.record(z.string(), RoleDefinitionSchema),
    summary: "List role definitions",
  }),
  route({
    id: "roles.get",
    family: "role",
    method: "GET",
    path: "/api/v1/roles/:roleId",
    params: IdParamsSchema,
    response: RoleDefinitionSchema,
    errors: ["role_not_found"],
    summary: "Read one role definition",
  }),
  route({
    id: "roles.updatePresentation",
    family: "role",
    method: "PATCH",
    path: "/api/v1/roles/:roleId/presentation",
    params: IdParamsSchema,
    body: UpdateRolePresentationCommandSchema,
    response: RoleDefinitionSchema,
    idempotency: "forbidden",
    errors: ["role_not_found"],
    summary: "Update role presentation",
  }),

  route({
    id: "runs.list",
    family: "run",
    method: "GET",
    path: "/api/v1/runs",
    query: StringQuerySchema,
    response: AgentRunSchema.array(),
    summary: "List runs with bounded filters",
  }),
  route({
    id: "runs.get",
    family: "run",
    method: "GET",
    path: "/api/v1/runs/:runId",
    params: IdParamsSchema,
    response: AgentRunSchema,
    errors: ["run_not_found"],
    summary: "Read one run",
  }),
  route({
    id: "runs.start",
    family: "run",
    method: "POST",
    path: "/api/v1/groups/:groupId/agents/:agentId/run",
    params: IdParamsSchema,
    body: StartAgentRunCommandSchema,
    response: AgentRunSchema,
    idempotency: "forbidden",
    errors: ["run_already_active", "agent_not_found"],
    summary: "Start an agent run",
    successStatus: 201,
  }),
  route({
    id: "runs.stop",
    family: "run",
    method: "DELETE",
    path: "/api/v1/groups/:groupId/agents/:agentId/run",
    params: IdParamsSchema,
    body: StopAgentRunCommandSchema,
    response: AgentRunSchema,
    idempotency: "forbidden",
    errors: ["run_not_found"],
    summary: "Stop an agent run",
  }),
  route({
    id: "runs.restart",
    family: "run",
    method: "POST",
    path: "/api/v1/runs/:runId/restart",
    params: IdParamsSchema,
    body: StartAgentRunCommandSchema,
    response: AgentRunSchema,
    idempotency: "forbidden",
    errors: ["run_not_found", "run_replaced"],
    summary: "Atomically restart one run",
    successStatus: 201,
  }),
  route({
    id: "runs.startAll",
    family: "run",
    method: "POST",
    path: "/api/v1/groups/:groupId/runs/start-all",
    params: IdParamsSchema,
    body: StartGroupRunsCommandSchema,
    response: StartGroupRunsResultSchema,
    idempotency: "forbidden",
    errors: ["group_not_found"],
    summary: "Start every configured agent",
  }),
  route({
    id: "runs.stopAll",
    family: "run",
    method: "POST",
    path: "/api/v1/groups/:groupId/runs/stop-all",
    params: IdParamsSchema,
    body: StopAgentRunCommandSchema,
    response: AgentRunSchema.array(),
    idempotency: "forbidden",
    errors: ["group_not_found"],
    summary: "Stop every active group run",
  }),
  route({
    id: "runs.restartAll",
    family: "run",
    method: "POST",
    path: "/api/v1/groups/:groupId/runs/restart-all",
    params: IdParamsSchema,
    body: StartGroupRunsCommandSchema,
    response: AgentRunSchema.array(),
    idempotency: "forbidden",
    errors: ["group_not_found"],
    summary: "Restart every active group run",
  }),
  route({
    id: "runs.interrupt",
    family: "run",
    method: "POST",
    path: "/api/v1/runs/:runId/interrupt",
    params: IdParamsSchema,
    body: InterruptAgentRunCommandSchema,
    response: EmptySchema,
    idempotency: "forbidden",
    errors: ["run_not_running", "terminal_unavailable"],
    summary: "Interrupt one run with Ctrl+C",
    successStatus: 204,
  }),

  route({
    id: "statuses.list",
    family: "status",
    method: "GET",
    path: "/api/v1/statuses",
    query: StringQuerySchema,
    response: AgentStatusSummarySchema.array(),
    summary: "List semantic agent statuses",
  }),
  route({
    id: "statuses.get",
    family: "status",
    method: "GET",
    path: "/api/v1/groups/:groupId/members/:memberId/status",
    params: IdParamsSchema,
    response: AgentStatusDetailSchema,
    errors: ["membership_not_found"],
    summary: "Read detailed semantic status",
  }),
  route({
    id: "statuses.acknowledge",
    family: "status",
    method: "POST",
    path: "/api/v1/groups/:groupId/members/:memberId/status/acknowledge",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: AgentStatusDetailSchema,
    idempotency: "optional",
    errors: ["membership_not_found"],
    summary: "Acknowledge the latest completion",
  }),

  route({
    id: "messages.submit",
    family: "message",
    method: "POST",
    path: "/api/v1/groups/:groupId/messages",
    params: IdParamsSchema,
    body: SubmitMessageCommandSchema,
    response: MessageSubmissionResultSchema,
    bodyLimit: 6_356_992,
    idempotency: "optional",
    errors: ["message_body_too_large", "membership_revision_stale"],
    summary: "Submit a durable group message",
    successStatus: 201,
  }),
  route({
    id: "messages.list",
    family: "message",
    method: "GET",
    path: "/api/v1/groups/:groupId/messages",
    params: IdParamsSchema,
    query: StringQuerySchema,
    response: MessagePageSchema,
    errors: ["invalid_message_cursor"],
    summary: "Read bounded visible message history",
  }),
  route({
    id: "messages.clear",
    family: "message",
    method: "DELETE",
    path: "/api/v1/groups/:groupId/messages",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: ClearMessageHistoryResultSchema,
    idempotency: "optional",
    errors: ["delivery_lease_active"],
    summary: "Clear retained message history",
  }),
  route({
    id: "messages.deliveries",
    family: "message",
    method: "GET",
    path: "/api/v1/messages/:messageId/deliveries",
    params: IdParamsSchema,
    response: DeliveryOutcomeSchema.array(),
    errors: ["message_not_found"],
    summary: "Read per-recipient delivery outcomes",
  }),

  route({
    id: "actions.create",
    family: "action",
    method: "POST",
    path: "/api/v1/agent-actions",
    body: CreateAgentActionCommandSchema,
    response: AgentActionSchema,
    idempotency: "required",
    errors: ["agent_action_target_offline", "agent_action_reporter_unavailable"],
    summary: "Create a durable exact-target action",
    successStatus: 201,
  }),
  route({
    id: "actions.get",
    family: "action",
    method: "GET",
    path: "/api/v1/agent-actions/:actionId",
    params: IdParamsSchema,
    response: AgentActionSchema,
    errors: ["agent_action_not_found"],
    summary: "Read one durable action",
  }),
  route({
    id: "actions.workspace",
    family: "action",
    method: "GET",
    path: "/api/v1/groups/:groupId/action-workspace",
    params: IdParamsSchema,
    response: AgentActionWorkspaceSchema,
    summary: "Read bounded action and wait state",
  }),
  route({
    id: "actions.cancel",
    family: "action",
    method: "POST",
    path: "/api/v1/agent-actions/:actionId/cancel",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: AgentActionSchema,
    idempotency: "optional",
    errors: ["agent_action_cancel_requires_ack"],
    summary: "Cancel a caller-owned pending action",
  }),
  route({
    id: "actions.wait",
    family: "action",
    method: "POST",
    path: "/api/v1/agent-actions/:actionId/wait",
    params: IdParamsSchema,
    body: WaitForAgentActionCommandSchema,
    response: UnknownObjectSchema,
    idempotency: "forbidden",
    errors: ["agent_action_not_found"],
    summary: "Wait for an exact action state",
  }),
  route({
    id: "waits.list",
    family: "wait",
    method: "GET",
    path: "/api/v1/open-waits",
    query: StringQuerySchema,
    response: OpenWaitSchema.array(),
    summary: "List open provider waits",
  }),
  route({
    id: "waits.reply",
    family: "wait",
    method: "POST",
    path: "/api/v1/open-waits/:waitId/reply",
    params: IdParamsSchema,
    body: ReplyOpenWaitCommandSchema,
    response: OpenWaitSchema,
    idempotency: "forbidden",
    errors: ["open_wait_replaced", "open_wait_reply_channel_unsupported"],
    summary: "Reply to one exact provider wait",
  }),

  route({
    id: "terminal.status",
    family: "terminal",
    method: "GET",
    path: "/api/v1/runs/:runId/terminal",
    params: IdParamsSchema,
    response: TerminalEndpointStatusSchema,
    errors: ["run_not_found"],
    summary: "Read terminal endpoint status",
  }),
  route({
    id: "terminal.read",
    family: "terminal",
    method: "GET",
    path: "/api/v1/runs/:runId/terminal/read",
    params: IdParamsSchema,
    query: StringQuerySchema,
    response: TerminalReadResultSchema,
    errors: ["terminal_unavailable", "run_replaced"],
    summary: "Read bounded terminal history",
  }),
  route({
    id: "terminal.checkpoints.list",
    family: "terminal",
    method: "GET",
    path: "/api/v1/terminal-checkpoints",
    response: TerminalCheckpointSchema.array(),
    summary: "List owner terminal checkpoints",
  }),
  route({
    id: "terminal.checkpoints.create",
    family: "terminal",
    method: "POST",
    path: "/api/v1/runs/:runId/terminal/checkpoints",
    params: IdParamsSchema,
    body: TerminalCheckpointCaptureSchema,
    response: TerminalCheckpointSchema,
    idempotency: "forbidden",
    errors: ["terminal_checkpoint_disabled"],
    summary: "Capture an owner terminal checkpoint",
    successStatus: 201,
  }),
  route({
    id: "terminal.checkpoints.get",
    family: "terminal",
    method: "GET",
    path: "/api/v1/terminal-checkpoints/:checkpointId",
    params: IdParamsSchema,
    response: TerminalCheckpointContentSchema,
    errors: ["terminal_checkpoint_not_found"],
    summary: "Read one owner terminal checkpoint",
  }),
  route({
    id: "terminal.checkpoints.delete",
    family: "terminal",
    method: "DELETE",
    path: "/api/v1/terminal-checkpoints/:checkpointId",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: EmptySchema,
    idempotency: "forbidden",
    errors: ["terminal_checkpoint_not_found"],
    summary: "Delete one owner terminal checkpoint",
    successStatus: 204,
  }),
  route({
    id: "artifact.preview",
    family: "terminal",
    method: "GET",
    path: "/api/v1/artifact-preview",
    query: StringQuerySchema,
    response: z.unknown(),
    errors: ["artifact_path_required", "artifact_not_found"],
    summary: "Read a bounded repository artifact preview",
  }),
  route({
    id: "terminal.stream",
    family: "terminal",
    method: "GET",
    path: "/api/v1/terminal-stream/:runId",
    params: IdParamsSchema,
    response: EmptySchema,
    errors: ["terminal_unavailable"],
    summary: "Open the versioned terminal WebSocket",
    successStatus: 101,
    transport: "websocket",
  }),

  route({
    id: "consoles.list",
    family: "console",
    method: "GET",
    path: "/api/v1/consoles",
    response: AdHocConsoleSessionSchema.array(),
    summary: "List ephemeral consoles",
  }),
  route({
    id: "consoles.get",
    family: "console",
    method: "GET",
    path: "/api/v1/consoles/:consoleId",
    params: IdParamsSchema,
    response: AdHocConsoleSessionSchema,
    errors: ["console_not_found"],
    summary: "Read one ephemeral console",
  }),
  route({
    id: "consoles.create",
    family: "console",
    method: "POST",
    path: "/api/v1/consoles",
    body: EmptyObjectSchema,
    response: AdHocConsoleSessionSchema,
    idempotency: "forbidden",
    summary: "Create an ephemeral console",
    successStatus: 201,
  }),
  route({
    id: "consoles.delete",
    family: "console",
    method: "DELETE",
    path: "/api/v1/consoles/:consoleId",
    params: IdParamsSchema,
    body: EmptyObjectSchema,
    response: EmptySchema,
    idempotency: "forbidden",
    errors: ["console_not_found"],
    summary: "Delete an ephemeral console",
    successStatus: 204,
  }),

  route({
    id: "repositories.list",
    family: "checkout",
    method: "GET",
    path: "/api/v1/repositories",
    response: RepositorySchema.array(),
    summary: "List discovered repositories",
  }),
  route({
    id: "checkouts.list",
    family: "checkout",
    method: "GET",
    path: "/api/v1/repositories/:repositoryId/checkouts",
    params: IdParamsSchema,
    response: CheckoutSchema.array(),
    summary: "List repository checkouts",
  }),
  route({
    id: "checkouts.open",
    family: "checkout",
    method: "POST",
    path: "/api/v1/checkouts/open",
    body: OpenCheckoutCommandSchema,
    response: WorktreeOperationResultSchema,
    idempotency: "forbidden",
    errors: ["checkout_not_found", "worktree_operation_in_progress"],
    summary: "Open a managed checkout",
  }),
  route({
    id: "worktrees.list",
    family: "worktree",
    method: "GET",
    path: "/api/v1/repositories/:repositoryId/worktrees",
    params: IdParamsSchema,
    response: WorktreeSchema.array(),
    summary: "List managed worktrees",
  }),
  route({
    id: "worktrees.create",
    family: "worktree",
    method: "POST",
    path: "/api/v1/worktrees",
    body: CreateWorktreeCommandSchema,
    response: WorktreeOperationResultSchema,
    idempotency: "forbidden",
    errors: ["worktree_operation_in_progress", "worktree_path_conflict"],
    summary: "Create a provenance-fenced worktree",
    successStatus: 201,
  }),
  route({
    id: "worktrees.delete",
    family: "worktree",
    method: "DELETE",
    path: "/api/v1/worktrees/:worktreeId",
    params: IdParamsSchema,
    body: RemoveWorktreeCommandSchema,
    response: WorktreeOperationResultSchema,
    idempotency: "forbidden",
    errors: ["worktree_not_found", "dirty_worktree_requires_force", "worktree_identity_changed"],
    summary: "Remove a provenance-fenced worktree",
  }),

  route({
    id: "events.subscribe",
    family: "events",
    method: "GET",
    path: "/api/v1/events",
    query: StringQuerySchema,
    response: EmptySchema,
    errors: ["invalid_event_sequence", "event_cursor_expired"],
    summary: "Subscribe to bounded replayable events",
    successStatus: 101,
    transport: "websocket",
  }),
] satisfies readonly ControlRouteDeclaration[]);

const routeById = new Map(CONTROL_ROUTE_REGISTRY.map((item) => [item.id, item]));

export function controlRoute(id: string): ControlRouteDeclaration {
  const declaration = routeById.get(id);
  if (declaration === undefined) throw new Error(`Unknown control route: ${id}`);
  return declaration;
}

export function matchControlRoute(
  method: string,
  path: string,
): ControlRouteDeclaration | undefined {
  return CONTROL_ROUTE_REGISTRY.find((declaration) => {
    if (declaration.method !== method) return false;
    const pattern = declaration.path
      .split("/")
      .map((segment) =>
        segment.startsWith(":") ? "[^/]+" : segment.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"),
      )
      .join("/");
    return new RegExp(`^${pattern}$`).test(path);
  });
}

function openApiPath(path: string): string {
  return path.replace(/:([A-Za-z0-9_]+)/g, "{$1}");
}

function jsonSchema(schema: z.ZodType): unknown {
  return z.toJSONSchema(schema, { unrepresentable: "any" });
}

export function generateControlOpenApi(): Record<string, unknown> {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const declaration of CONTROL_ROUTE_REGISTRY) {
    const path = openApiPath(declaration.path);
    const methods = (paths[path] ??= {});
    const bodySchema = declaration.schemas.body;
    methods[declaration.method.toLowerCase()] = {
      operationId: declaration.openapi.operationId,
      summary: declaration.openapi.summary,
      tags: declaration.openapi.tags,
      security:
        declaration.principal === "operator" ? [{ bearerAuth: [] }, { portalSession: [] }] : [],
      "x-nanasa-principal": declaration.principal,
      "x-nanasa-body-limit": declaration.bodyLimit,
      "x-nanasa-idempotency": declaration.idempotency,
      "x-nanasa-errors": declaration.errors,
      ...(bodySchema instanceof z.ZodUndefined
        ? {}
        : {
            requestBody: {
              required: true,
              content: { "application/json": { schema: jsonSchema(bodySchema) } },
            },
          }),
      responses: {
        [String(declaration.openapi.successStatus)]: {
          description: "Success",
          ...(declaration.openapi.successStatus === 204 || declaration.openapi.successStatus === 101
            ? {}
            : {
                content: {
                  "application/json": { schema: jsonSchema(declaration.schemas.response) },
                },
              }),
        },
        default: {
          description: "Versioned control error",
          content: { "application/json": { schema: { type: "object" } } },
        },
      },
    };
  }
  return {
    openapi: "3.1.0",
    info: { title: "Nanasa Control API", version: "1" },
    servers: [{ url: "/" }],
    paths,
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer" },
        portalSession: { type: "apiKey", in: "cookie", name: "nanasa_operator" },
      },
    },
  };
}
